### ISSUE TITLE
The scala installation is missing /release

### ISSUE THREAD

**Issue by markhkim** [markhkim/scripts#1]
[debian_ubuntu_mint_setup.sh](https://github.com/markhkim/scripts/blob/master/debian_ubuntu_mint_setup.sh) installs a functional copy of Scala. Upon running scala, however,
`cat: /release: No such file or directory`
is prompted before the scala shell executes.

**Comment by timhavens** [comment]
JAVA_HOME should be set, and in there should be a file name release.  My java install didn't have that file, so I just created one, and this goes away.

**Comment by markhkim** [comment]
@timhavens That did the trick! Thanks for the tip.
